config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  
  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy 
    @doc.destroy
    redirect_to docs_path
  end

  private
    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
.container.mt-3
  = simple_form_for @doc do |f|
    = f.input :title 
    = f.input :content
    .container.mt-3
      = f.button :submit, class: "button is-success is-outlined"
        

app/views/docs/edit.html.haml
.container.mt-3
  %h1.subtitle Fix Documment

  = render 'form'

  = link_to "Cancel", doc_path, class: "button is-danger is-outlined mt-3"    

app/views/docs/index.html.haml
- unless @docs.blank?
  - @docs.each do |doc|
    .box.container.mt-3
      %article
        .media-content
          %strong= link_to doc.title, doc
          %p= time_ago_in_words(doc.created_at)
          %p= truncate(doc.content, length:50) 
- else
  .container.mt-3
    %h2 Create a doc!
    %p Start creating documents for your thogths and your grate %Ideas!
    %button.button= link_to "Create Doc", new_doc_path 
  

app/views/docs/new.html.haml
.container.mt-3
  %h1.subtitle New Document

  = render 'form'

app/views/docs/show.html.haml
.container.mt-3	
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)
    .container.mt-2
      %button.button.is-primary.is-outlined.is-small= link_to "All Documments", docs_path
      %button.button.is-link.is-outlined.is-small= link_to "Fix Documments", edit_doc_path(@doc)
      %button.button.is-danger.is-outlined.is-small= link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your Daily Work %Notes!
  = stylesheet_link_tag 'application', media: 'all', 'data-turbo-links' => true
  = javascript_pack_tag 'application', 'data-turbo-links' => true
  = csrf_meta_tags
%body
  %header
    .navbar.is-light
      .navbar-brand
        = link_to "FileCabinet", root_path, id: "logo", class: "navbar-item"

      %nav.navbar-end
        - if user_signed_in?
          = link_to "Create Documment", new_doc_path, class: "navbar-item"
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-item" 
        
        - else
          = link_to "Log In", new_user_session_url, class: "navbar-item"

  
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
%section.pt-3.pb-3
  .container
    .card
      .card-image
        %figure.image.is-2by1

          = image_tag 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80', alt: '', height: '', width: '', class: ''
      .card-content
        %h2.title File Cabinet
        %p File Cabinet is a thoghts manager to express your feeling and ideas in an easy way!
        %button.button.is-light= link_to "Please feel free to sign up!", new_user_registration_path

%section.hero.is-dark.is-bold
  .hero-body
    .container
      %h1.title File Cabinet 
      %h2.subtitle Organazing you thoughs, Always!
      %button.button.is-primary.is-light.is-medium= link_to "Join Us", new_user_registration_path